---
- name: Install Zookeeper
  yum: name={{ item }} state=installed
  with_items:
    - mesosphere-zookeeper

- name: Configure the master standalone
  copy:
    content: "1"
    dest: "/var/lib/zookeeper/myid"
  notify: restart zookeeper

- name: Start Zookeeper
  service: name=zookeeper state=started enabled=yes

