---
- name: Install Mesos and Friends
  yum: name={{ item }} state=latest
  with_items:
    - marathon
    - chronos

- name: Enable Mesos Master
  service: name=mesos-master state=started enabled=yes

- name: Disable Mesos Slave
  service: name=mesos-slave state=stopped enabled=no

