---
- name: Configure the cluster name
  copy:
    content: "{{ cluster_name }}"
    dest: /etc/mesos-master/cluster
  notify: restart mesos-master

- name: Configure the bind interface
  copy:
    content: "{{ hostvars[inventory_hostname]['ansible_' + bind_interface].ipv4.address }}"
    dest: /etc/mesos-master/ip
  notify: restart mesos-master

- name: Enable Mesos Master
  service: name=mesos-master state=started enabled=yes

- name: Disable Mesos Slave
  service: name=mesos-slave state=stopped enabled=no

