---
- name: Update to latest device-mapper
  yum: name=device-mapper state=latest

- name: Install Docker
  yum: name=docker state=installed

- name: Start Docker Daemon
  service: name=docker state=started enabled=yes

